apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-nginx
  name: {{ .Value.service.name }} 
spec:
  ports:
  - name: "80"
    port: {{ .Value.service.port }}
    protocol: {{ .Value.service.protocol }}
    targetPort: 80
  selector:
    app: {{ .Values.deploy.name }}
  type: {{ .Value.service.type }}
